name = "Vanilla Patchcraft"
author = "xinchen"
version = "1.1.10"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "37e92c680b423fa576660c607dd8dd1d46d1a09c3316889ee5a59bd61a13e568"

[versions]
fabric = "0.18.5"
minecraft = "1.21.11"

[options]
acceptable-game-versions = ["1.21.10"]
