name = "Vanilla Patchcraft"
author = "xinchen"
version = "1.1.9"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9cd962d680e0b81270998c171553d12f27a73a23a4b46ef3f026a43a6de67d9d"

[versions]
fabric = "0.18.4"
minecraft = "1.21.11"

[options]
acceptable-game-versions = ["1.21.10"]
