name = "Vanilla Patchcraft"
author = "xinchen"
version = "1.1.8"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e65a8fbc8a9e58d29111e6ef774384ecbcc9841ff7026e6463935c6710974c79"

[versions]
fabric = "0.18.4"
minecraft = "1.21.11"

[options]
acceptable-game-versions = []
