name = "Vanilla Patchcraft"
author = "xinchen"
version = "2.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "28cd37231263237ad0e3d9f3c0c0cc9a0eaf2b52b86ea088e229957530bfaf0c"

[versions]
fabric = "0.19.2"
minecraft = "26.1.2"

[options]
acceptable-game-versions = ["26.1"]
