name = "Vanilla Patchcraft"
author = "xinchen"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "206fc9609d68fd71bf404bf7bd1cb096c31d82af25e551a799adce4779cb16e0"

[versions]
fabric = "0.19.2"
minecraft = "26.1.2"

[options]
acceptable-game-versions = ["26.1"]
